# Generated by Django 4.1 on 2022-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='value_currency',
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
