# Generated by Django 4.1 on 2022-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_questiondata_value_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=25),
        ),
    ]
